name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.9.5"
        enable-cache: true
    - name: Install the project
      run: uv sync --locked
    - name: Build project
      run: uv build
    - name: Publish to PyPI
      run: uv publish
