name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Install Poetry
      uses: abatilo/actions-poetry@v3
      with:
        poetry-version: 2.1.3
    - name: Install project
      run: poetry install --only main
    - name: Build project
      run: poetry build
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: Python Wheel
        path: "dist/*.whl"
    - name: Deploy release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        prerelease: false
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          dist/*.whl
    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish
